REPORT-904 - Added timezone offset parameter to report request
openmrs/openmrs-module-reportingui pull request #25
Opened 2023-12-05 17:29 UTC by icrc-psousa

2023-12-19 10:40 UTC, icrc-psousa commented
Hi @mseaton perhaps you can give your input here. This PR adds a parameter to the `ReportRequest` however, the parameter seems not to be making its way to the report processing stage.

With this code, everything seems to be functioning correctly. The new `timezoneOffset` parameter is successfully added to the `ReportRequest` and properly transmitted to the reporting module. However, an issue arises when the report request is queued in the database and subsequently retrieved. It appears that the `timezoneOffset` parameter is lost during the retrieval of the request for processing.

After the request is saved into the database, I observe the following within the `REPORT_DEFINITION_PARAMETERS` column in the `REPORTING_REPORT_REQUEST` table:

```
<map id="1">
  <entry>
    <string>endDate</string>
    <date id="2">2023-12-21 00:00:00 UTC</date>
  </entry>
  <entry>
    <string>timezoneOffset</string>
    <string>+00:00</string>
  </entry>
  <entry>
    <string>startDate</string>
    <date id="3">2023-11-01 00:00:00 UTC</date>
  </entry>
</map>
```

The `timezoneOffset` lacks an id, and upon entity loading, only the `startDate` and `endDate` parameters are being taken into account.
@mseaton  at 1st glance, do you notice any potential issues within the code on this PR that might be causing this problem?

2024-01-02 14:30 UTC, mseaton commented
> at 1st glance, do you notice any potential issues within the code on this PR that might be causing this problem

No, not really.  I don't think the `id` is the issue.  As you can see, none of the other String properties have an id either.  The id is not something used by the reporting module, it is just an implementation detail of xstream.  Have you actually confirmed via debugging that when this is deserialized that the timezoneOffset is not retrieved?  It is more likely that it is not being properly mapped through to the relevant definition.

2024-01-02 15:48 UTC, mseaton requested changes

2024-01-02 15:48 UTC, mseaton commented on omod/src/main/java/org/openmrs/module/reportingui/page/controller/RunReportPageController.java
> +        if (clientTimezone.isEmpty()) {
This is not null-safe

2024-01-16 09:39 UTC, icrc-psousa commented
> > at 1st glance, do you notice any potential issues within the code on this PR that might be causing this problem
> 
> No, not really. I don't think the `id` is the issue. As you can see, none of the other String properties have an id either. The id is not something used by the reporting module, it is just an implementation detail of xstream. Have you actually confirmed via debugging that when this is deserialized that the timezoneOffset is not retrieved? It is more likely that it is not being properly mapped through to the relevant definition.

Upon further analysis, the problem was on the report definition saved on the database, on the `serialized_object` table. It was missing the timezone parameter, hence it was discarded even though it was present on the `reporting_report_request`.

@mseaton @ibacher

2024-01-16 09:39 UTC, closed without merging

2024-01-16 09:40 UTC, icrc-psousa commented
Abandoning this PR as the issue was tackled using a different approach.